#############################################################################
# Makefile for building: loiq
# Generated by qmake (2.01a) (Qt 4.6.3) on: ?? ???? 18 22:51:01 2011
# Project:  loiq.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile loiq.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -D_REENTRANT -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -O2 -D_REENTRANT -Wall -W $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -Isrc -Isrc -Isrc
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = src/

####### Files

SOURCES       = src/httpflooder.cpp \
		src/main.cpp \
		src/main_window.cpp \
		src/synapse.cpp \
		src/xppflooder.cpp src/moc_httpflooder.cpp \
		src/moc_main_window.cpp \
		src/moc_synapse.cpp \
		src/moc_xppflooder.cpp \
		src/qrc_loiq.cpp
OBJECTS       = src/httpflooder.o \
		src/main.o \
		src/main_window.o \
		src/synapse.o \
		src/xppflooder.o \
		src/moc_httpflooder.o \
		src/moc_main_window.o \
		src/moc_synapse.o \
		src/moc_xppflooder.o \
		src/qrc_loiq.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		loiq.pro
QMAKE_TARGET  = loiq
DESTDIR       = 
TARGET        = loiq

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): src/ui_main_window.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: loiq.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtNetwork.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile loiq.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtNetwork.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile loiq.pro

dist: 
	@$(CHK_DIR_EXISTS) src/loiq1.0.0 || $(MKDIR) src/loiq1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) src/loiq1.0.0/ && $(COPY_FILE) --parents src/httpflooder.h src/main_window.h src/synapse.h src/xppflooder.h src/loiq1.0.0/ && $(COPY_FILE) --parents loiq.qrc src/loiq1.0.0/ && $(COPY_FILE) --parents src/httpflooder.cpp src/main.cpp src/main_window.cpp src/synapse.cpp src/xppflooder.cpp src/loiq1.0.0/ && $(COPY_FILE) --parents src/main_window.ui src/loiq1.0.0/ && $(COPY_FILE) --parents translations/loiq-en_US.ts translations/loiq-ru_RU.ts src/loiq1.0.0/ && (cd `dirname src/loiq1.0.0` && $(TAR) loiq1.0.0.tar loiq1.0.0 && $(COMPRESS) loiq1.0.0.tar) && $(MOVE) `dirname src/loiq1.0.0`/loiq1.0.0.tar.gz . && $(DEL_FILE) -r src/loiq1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: src/moc_httpflooder.cpp src/moc_main_window.cpp src/moc_synapse.cpp src/moc_xppflooder.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) src/moc_httpflooder.cpp src/moc_main_window.cpp src/moc_synapse.cpp src/moc_xppflooder.cpp
src/moc_httpflooder.cpp: src/httpflooder.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/httpflooder.h -o src/moc_httpflooder.cpp

src/moc_main_window.cpp: src/ui_main_window.h \
		src/xppflooder.h \
		src/httpflooder.h \
		src/synapse.h \
		src/main_window.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/main_window.h -o src/moc_main_window.cpp

src/moc_synapse.cpp: src/synapse.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/synapse.h -o src/moc_synapse.cpp

src/moc_xppflooder.cpp: src/xppflooder.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/xppflooder.h -o src/moc_xppflooder.cpp

compiler_rcc_make_all: src/qrc_loiq.cpp
compiler_rcc_clean:
	-$(DEL_FILE) src/qrc_loiq.cpp
src/qrc_loiq.cpp: loiq.qrc \
		translations/loiq-ru_RU.qm \
		translations/loiq-en_US.qm \
		images/LOIC.ico \
		images/LOIC.png
	/usr/bin/rcc -name loiq loiq.qrc -o src/qrc_loiq.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: src/ui_main_window.h
compiler_uic_clean:
	-$(DEL_FILE) src/ui_main_window.h
src/ui_main_window.h: src/main_window.ui
	/usr/bin/uic-qt4 src/main_window.ui -o src/ui_main_window.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

src/httpflooder.o: src/httpflooder.cpp src/httpflooder.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/httpflooder.o src/httpflooder.cpp

src/main.o: src/main.cpp src/xppflooder.h \
		src/main_window.h \
		src/ui_main_window.h \
		src/httpflooder.h \
		src/synapse.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/main.o src/main.cpp

src/main_window.o: src/main_window.cpp src/main_window.h \
		src/ui_main_window.h \
		src/xppflooder.h \
		src/httpflooder.h \
		src/synapse.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/main_window.o src/main_window.cpp

src/synapse.o: src/synapse.cpp src/synapse.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/synapse.o src/synapse.cpp

src/xppflooder.o: src/xppflooder.cpp src/xppflooder.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/xppflooder.o src/xppflooder.cpp

src/moc_httpflooder.o: src/moc_httpflooder.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/moc_httpflooder.o src/moc_httpflooder.cpp

src/moc_main_window.o: src/moc_main_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/moc_main_window.o src/moc_main_window.cpp

src/moc_synapse.o: src/moc_synapse.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/moc_synapse.o src/moc_synapse.cpp

src/moc_xppflooder.o: src/moc_xppflooder.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/moc_xppflooder.o src/moc_xppflooder.cpp

src/qrc_loiq.o: src/qrc_loiq.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/qrc_loiq.o src/qrc_loiq.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/bin/ || $(MKDIR) $(INSTALL_ROOT)/usr/bin/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)"
	-$(STRIP) "$(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/bin/ 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

